#ifndef IMAGERECOGNITION_GLOBAL_H
#define IMAGERECOGNITION_GLOBAL_H

#if defined(IMAGERECOGNITION_LIBRARY)
#  define IMAGERECOGNITIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGERECOGNITIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGERECOGNITION_GLOBAL_H
